config:
  password_pepper: ""
  hcaptcha:
    sitekey: ""
    secret: ""
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 
  emails:
    support: support@example.com
    security: security@example.com
    dmca: dmca@example.com

settings:
  deployment: TESTING
  site:
    name: Open Booru
    hostname: localhost
    port: 57255
  jwt:
    expiration: 86400 # Token Expiration time in seconds
  otp:
    valid_window: 1 # The previous N OTP codes are valid
  search:
    max_limit: 100 # Max number of results per search
  posts:
    required_aprroval: true # Posts require moderator approval beofre being visible

encoding:
  video:
    ffmpeg_args:
      format: webp
      vcodec: libvpx
      acodec: libvorbis
      srf: 24
    preview_duration: 5 # How long to preview the video
  image:
    full:
      lossless: true # Should webp be lossless
      quality: 100 # Re-encoded webp quality (1-100/lossless)
      max_width: 4000 # max width before downscaling
      max_height: 4000 # max height before downscaling
    preview:
      lossless: false
      quality: 90
      max_width: 1600
      max_height: 1600
    thumbnail:
      lossless: false
      quality: 80
      max_width: 250
      max_height: 250



testing:
  value:
    str: sample text
    int: 64
    float: 6.4
    bool: false
    array: [1,2,3]
  type: 
    str: ""
    int: 0
    float: 0.0
    bool: true
    array: []
