config:
  password_pepper: ""
  hcaptcha:
    sitekey: ""
    secret: ""
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 0

settings:
  deployment: TESTING
  password:
    min_length: 8
    strength: 0.3 #
  site:
    name: Open Booru
    hostname: 0.0.0.0
    port: 57255
  jwt:
    jwt_secret: "./data/jwt.prev" # Used to sign JWT, ensure it's long and secure
    expiration: 86400 # Token Expiration time in seconds
  otp:
    valid_window: 1 # The previous N OTP codes are valid
  posts:
    required_aprroval: true
    thumbnail:
      quality: 85 # 1-100
      max_dimensions: [250,250] # Max dimensions for downscaling
    preview:
      quality: 95
      max_dimensions: [1600,1600]
    full:
      quality: 100
      max_dimensions: [4000,4000]

testing:
  value:
    str: sample text
    int: 64
    float: 6.4
    bool: false
    array: [1,2,3]
  type: 
    str: ""
    int: 0
    float: 0.0
    bool: true
    array: []