config:
  site:
    name: Open Booru
    hostname: "localhost"
    port: 8443
  ssl:
    enabled: false
    key: ""
    cert: ""
  password_pepper: ""
  hcaptcha:
    sitekey: ""
    secret: ""
  aws:
    id: ""
    secret: ""
    region: "eu-west-2"
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 25

database:
  choice: "mongodb" # What database to use
  mongodb:
    name: "OpenBooru" # Name of the database in mongodb
    host: "slate"
    port: 27017
    wipe_on_startup: false # Wipe the database on startup, useful for testing


email:
  template_paths:
    email_verification: "./data/emails/email_verification.html"
    password_reset: "./data/emails/password_reset.html"


posts:
  search_max_limit: 100 # Max number of results per search
  import:
    local: # Import posts from local import directory
      enabled: true
    gelbooru: # Import posts from any gelbooru 2.0 site
      enabled: true
      website: safebooru.org # Examples: safebooru.org, rule34.xxx
      searches: [
        "sort:score asami_sato -bra -bikini",
        "pharah_(overwatch) mercy_(overwatch) yuri",
        "widowmaker_(overwatch) tracer_(overwatch) yuri -underwear",
        "sombra_(overwatch) yuri"
      ]
      limit: null # null for no limit

storage:
  method: "local" # Valid methods: s3, local
  s3:
    bucket-name: "openbooru" # Ensure name is valid

authentication:
  token_expiration: 86400 # Login Token Expiration time in seconds
  password_requirements: # Use null to disable check
    min_length: 8 # Maximum length of password
    max_length: 128 # Maximum length of password
    score: 3
    # 1 is increibly vulnerable, 4 is very secure
    # Based on https://github.com/dropbox/zxcvbn

thumbnail:
  lossless: false
  quality: 80
  max_width: 250
  max_height: 250

image:
  full:
    lossless: true # Should webp be lossless
    quality: 100 # Re-encoded webp quality (1-100/lossless)
    max_width: 4000 # max width before downscaling
    max_height: 4000 # max height before downscaling
  preview:
    lossless: false
    quality: 90
    max_width: 1600
    max_height: 1600

animation:
  lossless: true
  quality: 100
  max_width: 4000
  max_height: 4000

video:
  full:
    reencode: false # Should the video be re-encoded to reduce filesize#TODO: implement
  preview:
    enabled: false # Should video previews be generated #TODO: implement
    duration: 5 # How long should the video preview be#TODO: implement
  thumbnail_offset: 10 # Perentage through the video for the thumbnail screenshot to be taken#TODO: implement

permissions:
  annonymous:
    - canViewPosts
    - canSearchPosts

  user:
    - canViewUsers
    - canSearchUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    
    - canCreateComments
    - canViewComments

  admin:
    - canViewUsers
    - canSearchUsers
    - canEditUsers
    - canDeleteUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    - canDeletePosts
    
    - canCreateComments
    - canViewComments
    - canDeleteComments
