version: "3.3"
services:
  email:
    build: namshi/smtp
    environment:
      - MAILNAME=openbooru.org
    ports:
      - "25:25"
  web:
    build: .
    ports:
      - "57255:57255"
    expose:
      - 57255
    depends_on:
      - email