version: "3.3"
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - ./data/mongo:/data/db:rw
  api:
    build: .
    ports:
      - "443:443"
    expose:
      - 443
    depends_on:
      - mongodb