version: "3.3"
services:
  mongodb:
    image: 'mongo:4.0.4'
    container_name: 'openbooru-mongodb'
    ports:
      - "27017:27017"
  api:
    build: .
    ports:
      - "443:443"
    expose:
      - 443
    depends_on:
      - mongodb