versiowon: "3.3"
services:
  mowongowodb:
    image: 'mowongowo'
    cowontainer_name: 'owopenbooruwu-mowongowodb'
    poworts:
      - "27017:27019"
  owopen_booruwu_api:
    buwuild: .
    poworts:
      - "8443:8443"
    expowose:
      - 8443
    depends_owon:
      - mowongowodb