# Read the Documentation: https://github.com/TheOpenBooru/api/blob/main/settings.md
config:
  site:
    display_name: Open Booru
    hostname: "slate"
    port: 8443
  ssl:
    enabled: false
    key: ""
    cert: ""
  password_pepper: ""
  hcaptcha:
    enabled: false
    sitekey: ""
    secret: ""
  aws:
    id: ""
    secret: ""
    region: "eu-west-2"
  mongodb:
    hostname: "localhost"
    port: 27017
    name: "openbooru"
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 25
  wipe_on_startup: false

database:
  choice: "mongodb"


email:
  template_paths:
    email_verification: "./data/emails/email_verification.html"
    password_reset: "./data/emails/password_reset.html"


posts:
  search:
    default_sort: "created_at"
    max_limit: 100
  import:
    local:
      enabled: false
      local_path: "./data/import"
    safebooru:
      enabled: true
      searches: [
        "asami_sato yuri -bra -bikini",
        "samus_aran yuri",
        "pharah_(overwatch) mercy_(overwatch) yuri",
        "widowmaker_(overwatch) tracer_(overwatch) yuri -underwear",
        "sombra_(overwatch) -katya_volskaya yuri",
      ]
      limit: null

storage:
  method: "local"
  local:
    path: "./data/storage"
  s3:
    bucket-name: "openbooru"

authentication:
  token_expiration: 86400
  password_requirements:
    min_length: 8
    max_length: 128
    score: 3 

encoding:
  thumbnail:
    lossless: false
    quality: 80
    max_width: 250
    max_height: 250

  image:
    full:
      lossless: true
      quality: 100
      max_width: 4000
      max_height: 4000
    preview:
      lossless: false
      quality: 90
      max_width: 1600
      max_height: 1600

  animation:
    lossless: true
    quality: 100
    max_width: 4000
    max_height: 4000

  video:
    full:
      reencode: false #TODO: Not implemented
    preview:
      enabled: false #TODO: Not implemented
      duration: 5 #TODO: Not implemented
    thumbnail_offset: 10 #TODO: implemented

permissions:
  annonymous:
    - canViewPosts
    - canSearchPosts

  user:
    - canViewUsers
    - canSearchUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    
    - canCreateComments
    - canViewComments

  admin:
    - canViewUsers
    - canSearchUsers
    - canEditUsers
    - canDeleteUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    - canDeletePosts
    
    - canCreateComments
    - canViewComments
    - canDeleteComments
