# Read the Dowocuwumentatiowon: https://githuwub.cowom/TheOWOpenBooruwu/api/blowob/main/settings.md
cowonfig:
  site:
    display_name: OWOpen Booru
    howostname: "slate"
    powort: 8443
  ssl:
    enabled: false
    key: ""
    cert: ""
  passwoword_pepper: ""
  hcaptcha:
    enabled: false
    sitekey: ""
    secret: ""
  aws:
    id: ""
    secret: ""
    regiowon: "euwu-west-2"
  mowongowodb:
    howostname: "lowocalhowost"
    powort: 27017
    name: "owopenbooruwu"
  smtp:
    email: ""
    passwoword: ""
    howostname: ""
    powort: 25
  wipe_owon_startuwup: false

database:
  chowoice: "mowongowodb"


email:
  template_paths:
    email_verificatiowon: "./data/emails/email_verificatiowon.html"
    passwoword_reset: "./data/emails/passwoword_reset.html"


powosts:
  search:
    defauwult_sowort: "created_at"
    max_limit: 100
  impowort:
    lowocal:
      enabled: false
      lowocal_path: "./data/impowort"
    hydruwus:
      enabled: false
      access_key: ""
      uwurl: "http://lowocalhowost:45869/"
      tags:
        - "system:everything"
    tuwumblr:
      enabled: false
      cowonsuwumer_key: ""
      cowonsuwumer_secret: ""
      blowogs:
        - pauwuladrawsnstuwuff
    safebooruwu:
      enabled: false
      searches: [
        "asami_satowo yuwuri -bra -bikini",
        "samuwus_aran yuwuri",
        "pharah_(owoverwatch) mercy_(owoverwatch) yuwuri",
        "widowowmaker_(owoverwatch) tracer_(owoverwatch) yuwuri -uwunderwear",
        "sowombra_(owoverwatch) -katya_vowolskaya yuwuri",
      ]
      limit: 100

stoworage:
  methowod: "lowocal"
  lowocal:
    path: "./data/stoworage"
  s3:
    buwucket-name: "owopenbooruwu"

auwuthenticatiowon:
  towoken_expiratiowon: 86400
  passwoword_requwuirements:
    min_length: 8
    max_length: 128
    scowore: 3 

encowoding:
  thuwumbnail:
    lowossless: false
    quwuality: 80
    max_width: 250
    max_height: 250

  image:
    fuwull:
      lowossless: truwue
      quwuality: 100
      max_width: 4000
      max_height: 4000
    preview:
      lowossless: false
      quwuality: 90
      max_width: 1600
      max_height: 1600

  animatiowon:
    lowossless: truwue
    quwuality: 100
    max_width: 4000
    max_height: 4000

  videowo:
    fuwull:
      reencowode: false #TOWODO: Nowot implemented
    preview:
      enabled: false #TOWODO: Nowot implemented
      duwuratiowon: 5 #TOWODO: Nowot implemented
    thuwumbnail_owoffset: 10 #TOWODO: implemented

permissiowons:
  annowonymowouwus:
    - canViewPowosts
    - canSearchPowosts

  uwuser:
    - canViewUWUsers
    - canSearchUWUsers
    
    - canCreatePowosts
    - canViewPowosts
    - canSearchPowosts
    - canEditPowosts
    
    - canCreateCowomments
    - canViewCowomments

  admin:
    - canViewUWUsers
    - canSearchUWUsers
    - canEditUWUsers
    - canDeleteUWUsers
    
    - canCreatePowosts
    - canViewPowosts
    - canSearchPowosts
    - canEditPowosts
    - canDeletePowosts
    
    - canCreateCowomments
    - canViewCowomments
    - canDeleteCowomments
