# Read the Documentation: https://github.com/TheOpenBooru/api/blob/main/settings.md
config:
  site:
    display_name: Open Booru
    hostname: "localhost"
    port: 8443
  ssl:
    enabled: false
    key: "./data/server.key"
    cert: "./data/server.crt"
  hcaptcha:
    enabled: true
    sitekey: "10000000-ffff-ffff-ffff-000000000001"
    secret: "0x0000000000000000000000000000000000000000"
  aws:
    id: ""
    secret: ""
    region: "eu-west-2"
  mongodb:
    hostname: "localhost"
    port: 27017
    name: "openbooru"
    username: ""
    password: ""
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 25
  wipe_on_startup: false


email:
  template_paths:
    email_verification: "./data/emails/email_verification.html"
    password_reset: "./data/emails/password_reset.html"


posts:
  search:
    default_sort: "created_at"
    max_limit: 100


tags:
  regenerate_on_startup: true
  minimum_count: 3
  valid_namespaces:
    - character
    - creator
    - meta
    - series
  tagging_service:
    enabled: false
    url: ""


importers:
  local:
    enabled: false
    local_path: "./data/import"
  hydrus:
    enabled: false
    access_key: ""
    url: ""
    tags:
      - "system:everything"
  safebooru:
    enabled: false
    limit: null
    searches:
      - rating:safe overwatch
  e621:
    enabled: false
    dump_location: ""
  rule34:
    enabled: false
    dump_location: ""
    proxy_format: ""


downloaders:
  e621:
    enabled: true
  rule34:
    enabled: true
  safebooru:
    enabled: true
  youtube:
    enabled: true
  file:
    enabled: true
  twitter:
    enabled: true
    bearer_token: ""
  tumblr:
    enabled: true
    consumer_key: ""
    consumer_secret: ""


storage:
  method: "local"
  local:
    path: "./data/storage"
  s3:
    bucket-name: ""


authentication:
  token_expiration: null
  password_policy:
    min_length: 8
    max_length: 128
    score: 3 


encoding:
  thumbnail:
    lossless: false
    quality: 80
    max_width: 250
    max_height: 250

  image:
    full:
      lossless: true
      quality: 100
      max_width: 4000
      max_height: 4000
    preview:
      lossless: false
      quality: 90
      max_width: 1600
      max_height: 1600

  animation:
    lossless: true
    quality: 100
    max_width: 4000
    max_height: 4000

  video:
    thumbnail_offset: 2


permissions:
  annonymous:
    canViewPosts:
    canSearchPosts:

  user:
    canViewUsers:
    canSearchUsers:
    
    canCreatePosts:
    canVotePosts:
    canViewPosts:
    canSearchPosts:
    canEditPosts:
    
    canCreateComments:
    canViewComments:

  admin:
    canViewUsers:
    canSearchUsers:
    canEditUsers:
    canDeleteUsers:
    
    canCreatePosts:
    canVotePosts:
    canViewPosts:
    canSearchPosts:
    canEditPosts:
    canDeletePosts:
    
    canCreateComments:
    canViewComments:
    canDeleteComments:
