config:
  site:
    display_name: Open Booru
    hostname: "localhost"
    port: 8443
  ssl:
    enabled: false
    key: ""
    cert: ""
  password_pepper: ""
  hcaptcha:
    enabled: false
    sitekey: ""
    secret: ""
  aws:
    id: ""
    secret: ""
    region: "eu-west-2"
  mongodb:
    hostname: "localhost"
    port: 27017
    name: "openbooru"
  smtp:
    email: ""
    password: ""
    hostname: ""
    port: 25

database:
  wipe_on_startup: false
  choice: "mongodb"


email:
  template_paths:
    email_verification: "./data/emails/email_verification.html"
    password_reset: "./data/emails/password_reset.html"


posts:
  search_max_limit: 100 # 
  import:
    local: # Import posts from local import directory
      enabled: false
      local_path: "./data/import" # The local path to import posts from
    gelbooru: # Import posts from any gelbooru 2.0 site
      enabled: true
      website: safebooru.org # Examples: safebooru.org, rule34.xxx
      searches: [
        "asami_sato yuri -bra -bikini",
        "pharah_(overwatch) mercy_(overwatch) yuri",
        "widowmaker_(overwatch) tracer_(overwatch) yuri -underwear",
        "sombra_(overwatch) yuri -katya_volskaya",
        "samus_aran yuri",
      ]
      limit: null # null for no limit

storage:
  method: "local" # Valid methods: s3, local
  local:
    path: "./data/storage" # The path to the local storage directory
  s3:
    bucket-name: "openbooru" # Ensure name is valid

authentication:
  token_expiration: 86400 # Login Token Expiration time in seconds
  password_requirements:
    min_length: 8 # Maximum length of password
    max_length: 128 # Maximum length of password
    score: 3 

encoding:
  thumbnail:
    lossless: false # 
    quality: 80 # 
    max_width: 250 #
    max_height: 250 # 

  image: # How image files are encoded
    full:
      lossless: true # Refer to thumbnail
      quality: 100 # Refer to thumbnail
      max_width: 4000 # Refer to thumbnail
      max_height: 4000 # Refer to thumbnail
    preview:
      lossless: false # Refer to thumbnail
      quality: 90 # Refer to thumbnail
      max_width: 1600 # Refer to thumbnail
      max_height: 1600 # Refer to thumbnail

  animation: # How animations (gifs) files are encoded
    lossless: true # Refer to thumbnail
    quality: 100 # Refer to thumbnail
    max_width: 4000 # Refer to thumbnail
    max_height: 4000 # Refer to thumbnail

  video: # How videos files are encoded
    full:
      reencode: false # Should the video be re-encoded to reduce filesize #TODO: Not implemented
    preview:
      enabled: false # Should video previews be generated #TODO: Not implemented
      duration: 5 # How long should the video preview be #TODO: Not implemented
    thumbnail_offset: 10 # Perentage through the video for the thumbnail screenshot to be taken #TODO: implemented

permissions: # What permissions each level gets
  # Avaliable Options are:
    # canViewUsers - Can view other user's profiles
    # canSearchUsers - Can search for users
    # canEditUsers - Can edit other user's accounts
    # canDeleteUsers - Can delete other user's accounts
    
    # canCreatePosts - Can create posts
    # canViewPosts - Can view posts
    # canSearchPosts - Can search for posts
    # canEditPosts - Can make edits to posts
    # canDeletePosts - Can delete other people's posts

    # canCreateComments - Can create comments on posts
    # canViewComments - Can view other people's comments on posts
    # canDeleteComments - Can delete other people's comments on posts
  annonymous: # Annonomous users, anyone can access
    - canViewPosts
    - canSearchPosts

  user: # User's with a normal account
    - canViewUsers
    - canSearchUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    
    - canCreateComments
    - canViewComments

  admin: # Site owners/admins
    - canViewUsers
    - canSearchUsers
    - canEditUsers
    - canDeleteUsers
    
    - canCreatePosts
    - canViewPosts
    - canSearchPosts
    - canEditPosts
    - canDeletePosts
    
    - canCreateComments
    - canViewComments
    - canDeleteComments
