
    def create(hash:str,*,src:str="") -> int:
        ...


    def get(*,id:int=None,md5:str=None) -> dict:
        ...
    
    def search(*,tags:list=[],orderby:str='creation',direction:str='',limit:int=10):
        ...
    def delete(id:int) -> dict:
        ...